// @ts-expect-error — generated by `opennextjs-cloudflare build`, so it does not
// exist until the build has run and has no types of its own.
import openNextWorker from '../.open-next/worker.js';

/**
 * The Worker entry point.
 *
 * `@opennextjs/cloudflare` generates a worker that exports `fetch` and nothing
 * else. Cloudflare Cron Triggers invoke `scheduled`, so a cron declared in
 * `wrangler.jsonc` against the generated worker alone would fire into a handler
 * that does not exist — silently, four times a day, while the keep-alive it was
 * meant to run never ran and the free-tier database paused after a quiet week.
 *
 * This entry adds that handler and delegates everything else unchanged. It is
 * deliberately the only hand-written Worker code in the project: the scheduled
 * jobs themselves are ordinary route handlers, testable and reachable over HTTP
 * like anything else.
 */

import { SCHEDULE, normalizeCron } from './schedule';

interface Env {
  CRON_SECRET?: string;
  NEXT_PUBLIC_SITE_URL?: string;
}

const worker = {
  fetch: openNextWorker.fetch,

  async scheduled(
    event: { cron: string; scheduledTime: number },
    env: Env,
    ctx: { waitUntil: (promise: Promise<unknown>) => void },
  ) {
    const path = SCHEDULE[normalizeCron(event.cron)];

    if (!path) {
      console.error(`no job mapped to cron "${event.cron}"`);
      return;
    }

    if (!env.CRON_SECRET) {
      // Worth shouting about: without the secret every scheduled request is
      // refused, and the keep-alive is the one job whose silent failure takes
      // the whole shop offline a week later.
      console.error('CRON_SECRET is not set — scheduled jobs cannot authenticate');
      return;
    }

    const base = env.NEXT_PUBLIC_SITE_URL ?? 'https://el-gomala.internal';

    const run = (async () => {
      const response = await openNextWorker.fetch(
        new Request(new URL(path, base), {
          headers: { authorization: `Bearer ${env.CRON_SECRET}` },
        }),
        env,
        ctx,
      );

      const body = await response.text();

      // Logged either way. A successful sweep reports what it removed, and a
      // failure is the only alarm this system has — Cloudflare records a
      // non-2xx scheduled invocation as failed.
      console.log(`${path} → ${response.status} ${body.slice(0, 500)}`);

      if (!response.ok) {
        throw new Error(`${path} failed with ${response.status}`);
      }
    })();

    ctx.waitUntil(run);
    await run;
  },
};

export default worker;
